---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: firefly-iii
  namespace: flux-system
spec:
  chart:
    spec:
      chart: firefly-iii
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: firefly-iii
        namespace: flux-system
  interval: 24h0m0s
  releaseName: firefly-iii
  targetNamespace: home-services
  values:
    image:
      repository: "fireflyiii/core"
      pullPolicy: Always
      tag: version-6.0.4
    persistence:
      enabled: true
      existingClaim: "firefly-pvc"
    config:
      # -- Set this to the name of a secret to load environment variables from. If defined, values in the secret will override values in config.env
      existingSecret: "firefly-iii-configuration"
      envValueFrom: {}
    env:
        DEFAULT_LANGUAGE: "en_US"
        DEFAULT_LOCALE: "equal"
        TZ: "Europe/Lisbon"
        TRUSTED_PROXIES: "**"
    ingress:
      enabled: true
      hosts:
        - firefly.${DOMAIN_NAME}
      paths:
        - path: "/"
      tls:
        - hosts:
            - firefly.${DOMAIN_NAME}
          secretName: ${DOMAIN_NAME/./-}-tls
