apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: nginx-reverse-proxy
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      server {
        listen 80;
        server_name domain.${DOMAIN_NAME};

        location / {
          proxy_pass http://papermc:8100;
        }
      }
    }
