apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-map
  namespace: home-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy
        image: caddy:latest
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
        volumeMounts:
        - mountPath: /usr/share/caddy
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: mcmap-pvc
