---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mcmap-pv
  namespace: home-services
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    server: nas.domain.com
    path: /export/kubernetes/home-services-mcmap
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcmap-pvc
  namespace: home-services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
  volumeName: mcmap-pv
