---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-config-pv
  namespace: home-services
spec:
  capacity:
    storage: 256M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    server: nas.${DOMAIN_NAME}
    path: /export/kubernetes/transmission-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config-pvc
  namespace: home-services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 256M
  volumeName: transmission-config-pv
