---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-downloads-pv
  namespace: home-services
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  nfs:
    server: nas.${DOMAIN_NAME}
    path: /export/kubernetes/transmission-downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads-pvc
  namespace: home-services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 100Gi
  volumeName: transmission-downloads-pv
