---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${DOMAIN_NAME/./-}
  namespace: home-services
spec:
  secretName: ${DOMAIN_NAME/./-}-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.${DOMAIN_NAME}"
  dnsNames:
    - "*.${DOMAIN_NAME}"
