---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-com
  namespace: home-services
spec:
  secretName: domain-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.domain.com"
  dnsNames:
    - "*.domain.com"
