apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.crds.yaml
  - helmrelease.yaml
  - cloudflare-token-secret.yaml
  - letsencrypt-cluster-issuer.yaml
