---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mealie
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mealie
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: geek-cookbook
        namespace: flux-system
  interval: 24h0m0s
  releaseName: mealie
  targetNamespace: home-services
  values:
    replicaCount: 1
    ingress:
      main:
        enabled: true
        hosts:
          - host: mealie.${DOMAIN_NAME}
            paths:
              - path: "/"
        tls:
          - hosts:
              - mealie.${DOMAIN_NAME}
            secretName: domain-com-tls

