---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
  interval: 24h0m0s
  releaseName: nfs-subdir-external-provisioner
  targetNamespace: default
  values:
    nfs:
      server: nas.${DOMAIN_NAME}
      path: /export/kubernetes
    # For creating the StorageClass automatically:
    storageClass:
      create: true
      # Set StorageClass as the default StorageClass
      defaultClass: true
      # Set access mode - ReadWriteOnce, ReadOnlyMany or ReadWriteMany
      accessModes: ReadOnlyMany

