---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: flux-system
spec:
  chart:
    spec:
      chart: portainer
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: portainer
  interval: 24h0m0s
  releaseName: portainer
  targetNamespace: home-services

  ingress:
    enabled: true
    hosts:
      - host: portainer.${DOMAIN_NAME}
        paths:
          - path: "/"
    tls:
      - hosts:
          - portainer.${DOMAIN_NAME}
        secretName: domain-com-tls