---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: miniflux
  namespace: flux-system
spec:
  chart:
    spec:
      chart: miniflux
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: geek-cookbook
        namespace: flux-system
  interval: 24h0m0s
  releaseName: miniflux
  targetNamespace: home-services
  values:
    env:
      - name: TZ
        value: UTC
      - name: RUN_MIGRATIONS
        value: '1'
      - name: CREATE_ADMIN
        value: '1'
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: miniflux-configuration
            key: DATABASE_URL
      - name: ADMIN_USERNAME
        valueFrom:
          secretKeyRef:
            name: miniflux-configuration
            key: ADMIN_USERNAME
      - name: ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: miniflux-configuration
            key: ADMIN_PASSWORD

    ingress:
      main:
        enabled: true
        hosts:
          - host: miniflux.domain.com
            paths:
              - path: "/"
        tls:
          - hosts:
              - miniflux.domain.com
            secretName: domain-com-tls

    postgresql:
      enabled: false
